# Generated by Django 2.2 on 2019-06-06 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogname', models.CharField(max_length=255)),
                ('dogbreedprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dogbreedentrydate', models.DateField()),
                ('dogbreedURL', models.URLField(blank=True, null=True)),
                ('dogbreeddescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'dogs',
                'db_table': 'dog',
            },
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogbreedname', models.CharField(max_length=255)),
                ('dogbreeddescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'dogbreeds',
                'db_table': 'dogbreed',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('dogbreedrating', models.SmallIntegerField()),
                ('reviewtext', models.TextField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogbreedapp.Dog')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='dogbreed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogbreedapp.DogBreed'),
        ),
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
